# Generated by Django 2.0.4 on 2018-04-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('delivery_fee', models.IntegerField(default=0)),
                ('billing_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.BillingInformation')),
                ('delivery_preferences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.DeliveryPreferences')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Discount')),
                ('code', models.CharField(max_length=128)),
            ],
            bases=('portal.discount',),
        ),
        migrations.CreateModel(
            name='RegisteredShopper',
            fields=[
                ('shopper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Shopper')),
                ('username', models.CharField(max_length=255)),
                ('passwordHash', models.CharField(max_length=255)),
            ],
            bases=('portal.shopper',),
        ),
        migrations.CreateModel(
            name='VisitorShopper',
            fields=[
                ('shopper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Shopper')),
            ],
            bases=('portal.shopper',),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Shopper'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.ProductCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(to='portal.Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='payment_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PaymentInformation'),
        ),
    ]
