# Generated by Django 2.0.4 on 2018-04-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180426_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.RenameField(
            model_name='registeredshopper',
            old_name='passwordHash',
            new_name='password_hash',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registeredshopper',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredshopper',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredshopper',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='portal.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='portal.ShoppingCart'),
        ),
    ]
