# Generated by Django 2.0.4 on 2018-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180426_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorShopper',
        ),
    ]
