# Generated by Django 2.0.4 on 2018-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_shoppingcart_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
