# Generated by Django 2.0.4 on 2018-04-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180428_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredshopper',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredshopper',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
