# Generated by Django 2.0.4 on 2018-04-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180428_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='discount',
            new_name='discounts',
        ),
    ]
