# Generated by Django 2.0.4 on 2018-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20180428_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='discounts',
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(to='portal.Discount'),
        ),
    ]
