# Generated by Django 2.0.4 on 2018-04-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20180428_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.ShoppingCart'),
        ),
    ]
