# Generated by Django 2.0.4 on 2018-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20180428_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
