# Generated by Django 2.0.4 on 2018-04-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_productcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInformation',
            fields=[
                ('paymentinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.PaymentInformation')),
                ('card_number', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=4)),
                ('expiration_date', models.DateField()),
            ],
            bases=('portal.paymentinformation',),
        ),
    ]
